sonar.projectKey=TaRgITay008_python-project-52
sonar.organization=targitay008
sonar.sources=.
sonar.exclusions=**/migrations/**, **/__pycache__/**, .venv/**, task_manager/settings.py
sonar.python.coverage.reportPaths=coverage.xml
